version: '3.9'
services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev -- auth
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: auth
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONFIG_ENV_FILE: ./apps/auth/.env.${NODE_ENV:-development}

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev -- api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: core
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONFIG_ENV_FILE: ./apps/api/.env.${NODE_ENV:-development}

  tts:
    build:
      context: .
      dockerfile: ./apps/tts/Dockerfile
      target: development
    command: npm run start:dev -- tts
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: tts
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONFIG_ENV_FILE: ./apps/tts/.env.${NODE_ENV:-development}

  stt:
    build:
      context: .
      dockerfile: ./apps/stt/Dockerfile
      target: development
    command: npm run start:dev -- stt
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: stt
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONFIG_ENV_FILE: ./apps/stt/.env.${NODE_ENV:-development}

  chatgpt:
    build:
      context: .
      dockerfile: ./apps/chatgpt/Dockerfile
      target: development
    command: npm run start:dev -- chatgpt
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: chatgpt
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CONFIG_ENV_FILE: ./apps/chatgpt/.env.${NODE_ENV:-development}

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lifeMateDoll
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
