services:
  core:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: Development
    command: npm run start:dev api
    ports:
      - "3000:3000" # Map container port to host port
    volumes:
      - .:/usr/src/app


