services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev -- auth
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: auth
    environment:
      NODE_ENV: development 

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: npm run start:dev -- api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./apps/chatgpt/.env:/usr/src/app/.env
    container_name: core
    environment:
      NODE_ENV: development 

  tts:
    build:
      context: .
      dockerfile: ./apps/tts/Dockerfile
      target: development
    command: npm run start:dev -- tts
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
      - ./apps/chatgpt/.env:/usr/src/app/.env
    container_name: tts
    environment:
      NODE_ENV: development 

  chatgpt:
    build:
      context: .
      dockerfile: ./apps/chatgpt/Dockerfile
      target: development
    command: npm run start:dev -- chatgpt
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - ./apps/chatgpt/.env:/usr/src/app/.env
    container_name: chatgpt
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lifeMateDoll
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
