name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335666258.dkr.ecr.us-east-1.amazonaws.com


        # Build and push Docker image for TTS
      - name: Build and push Docker image for TTS
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t api-tts:${IMAGE_TAG} -f apps/tts/Dockerfile .
          docker tag api-tts:${IMAGE_TAG} 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-tts:${IMAGE_TAG}
          docker push 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-tts:${IMAGE_TAG}
          echo "TTS_IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      # Verify tts image contents
      - name: Verify Tts image contents
        run: |
          docker run -t --rm 730335666258.dkr.ecr.us-east-1.amazonaws.com/api-tts:${{ env.TTS_IMAGE_TAG }} sh -c "ls /usr/src/app/dist/apps"

      # Register new task definition for Tts
      - name: Register Task Definition for Tts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition tts | \
          jq '.taskDefinition | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .deregisteredAt, .registeredBy)')
          NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | \
          jq --arg IMAGE_TAG "730335666258.dkr.ecr.us-east-1.amazonaws.com/api-tts:${{ env.TTS_IMAGE_TAG }}" '.containerDefinitions[0].image = $IMAGE_TAG')
          echo $NEW_TASK_DEFINITION > new-tts-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-tts-task-def.json



        # Update ECS Service for tts
      - name: Update ECS Service for tts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          TASK_REVISION=$(aws ecs describe-task-definition --task-definition tts | jq -r '.taskDefinition.revision')
          aws ecs update-service \
            --cluster my-app-cluster \
            --service tts \
            --task-definition tts:${TASK_REVISION} \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-0e84ae40779095680],securityGroups=[sg-0271630958447aeae],assignPublicIp=ENABLED}" \
            --force-new-deployment
