name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 730335666258.dkr.ecr.$AWS_REGION.amazonaws.com

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t api:latest .
          docker tag api:latest 730335666258.dkr.ecr.$AWS_REGION.amazonaws.com/api:latest
          docker push 730335666258.dkr.ecr.$AWS_REGION.amazonaws.com/api:latest

      # Update ECS service
      - name: Update ECS service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service --cluster my-app-cluster --service api --force-new-deployment
